#!/bin/sh

set -x -e

save_excursion() {
    current=`git branch | awk '/^\*/ { print $2 }'`
    touch .ensure-there-is-something-to-stash
    git stash -a
    "$@"
    git checkout "$current"
    git stash pop
    rm .ensure-there-is-something-to-stash
}

foreach_branch() {
    for i in `git branch | cut -c3- | grep -v master`; do
	"$@" "$i"
    done
}

all_branches() {
    save_excursion foreach_branch "$@"
}

all_branches git rebase master
