#!/bin/sh

set -x -e

upstream="upstream"

target() {
    git remote show -n "$upstream" | awk -F/ '/Push/ { print $4 "/" $5 }'
}

user() {
    git remote show -n origin | awk -F/ '/Push/ { print $4 }'
}

github_pull_request() {
    branch=`git branch | awk '/^\*/ { print $2 }'`
    user=`user`
    git push origin "$branch"

    if -n "$1"; then
	message=`mktemp`
	"$EDITOR" "$message"
	title=`head -1 "$message"`
	body=`tail -n +2 "$message"`
	data="{ \"title\": \"$title\", \"body\": \"$body\","
    else
	issue="$1"
	data="{ \"issue\": \"$issue\","
    fi

    head="$user:$branch"
    base="master"
    data="$data \"head\": \"$head\", \"base\": \"$base\" }"

    eval `echo "" | git credential-cache get`
    url="https://api.github.com/repos/`target`/pulls"
    curl -s -u "$username:$password" -X POST -d "$data" "$url"
}

get_parent() {
    awk -F\" 'BEGIN { p=0 } /parent/ { p=1 } p && /full_name/ { print $4; exit }'
}

github_parent() {
    curl -N -s "https://api.github.com/repos/$1" | get_parent
}

git_clone_dir() {
    git clone "https://github.com/$1" $2 2>&1 | awk -F\' '/Cloning into/ { print $2 }'
}

github_clone() {
    dir=`git_clone_dir "$1" "$2"`
    parent=`github_parent "$1"`
    test -n "$parent" && (cd $dir; git remote add upstream "https://github.com/$parent")
}

case "$1" in
    pr) github_pull_request "$2" ;;
    clone) github_clone "$2" "$3" ;;
esac
