#!/bin/bash

set -x -e

current_branch() {
    git branch | awk '/^\* / { print $2 }'
}

save_excursion() {
    current=`git branch | awk '/^\*/ { print $2 }'`
    touch .ensure-there-is-something-to-stash
    git stash save -a git-pull-all
    "$@"
    git checkout "$current"
    git stash pop -q
    rm .ensure-there-is-something-to-stash
}

has_remote() {
    git remote | grep "$1" >/dev/null
}

fast_forward() {
    git checkout "$2"
    git merge --ff-only "$1"/"$2"
}

pull_from() {
    has_remote "$1" || return 0
    git fetch "$1"
    fast_forward "$1" master
}

pull_all() {
    pull_from origin
    pull_from upstream
}

save_excursion pull_all
