#!/bin/sh

set -x -e

upstream="upstream"

fail() {
    echo "$1" 1>&2
    exit 1
}

github_api() {
    eval `echo "host=github.com" | git credential-cache get`
    url="https://api.github.com/$2"
    curl -s -u "$username:$password" -X "$1" -d "$3" "$url"
}

target() {
    git remote show -n "$upstream" | awk -F/ '/Push/ { print $4 "/" $5 }'
}

user() {
    git remote show -n origin | awk -F/ '/Push/ { print $4 }'
}

get_number() {
    awk -F: '/"number":/ { print $2 }' | tr -d ' ,'
}

get_branch_pr_number() {
    while read i; do
	case "$i" in
	    *'"number":'*) number="$i" ;;
	    *'"label":'*"$1"*) label="$i" ;;
	    *'"label":'*) number="" ;;
	esac
	if test -n "$number" && test -n "$label"; then
	    echo "$number" | get_number
	    number=""
	    label=""
	fi
    done
}

current_branch() {
    git branch | awk '/^\* / { print $2 }'
}

github_pull_request() {
    branch=`current_branch`
    user=`user`
    git push origin "$branch"

    if test -z "$1"; then
	message=`mktemp`
	echo "# The first line will become the title.  The rest will be the description." > "$message"
	echo "#" >> "$message"
	echo "# Commits:" >> "$message"
	git log --oneline upstream/master..HEAD | sed 's/^/# /' >> "$message"
	"$EDITOR" "$message"
	grep -v '^#' "$message" > "$message.2"
	title=`head -1 "$message.2"`
	body=`tail -n +2 "$message.2" | sed 's/$/ \\\\n/'`
	rm -f "$message" "$message.2"
	data="{ \"title\": \"$title\", \"body\": \"$body\","
    else
	issue="$1"
	data="{ \"issue\": \"$issue\","
    fi

    head="$user:$branch"
    base="master"
    echo "$data \"head\": \"$head\", \"base\": \"$base\" }" > TMP
    github_api POST "repos/`target`/pulls" "@TMP" | get_number
    rm -f TMP
}

get_parent() {
    awk -F\" 'BEGIN { p=0 } /parent/ { p=1 } p && /full_name/ { print $4; exit }'
}

github_parent() {
    github_api GET "repos/$1" "" | get_parent
}

git_clone_dir() {
    git clone "https://github.com/$1" $2 2>&1 | awk -F\' '/Cloning into/ { print $2 }'
}

github_clone() {
    dir=`git_clone_dir "$1" "$2"`
    parent=`github_parent "$1"`
    test -n "$parent" && (cd $dir; git remote add upstream "https://github.com/$parent")
}

github_new_repo() {
    github_api POST user/repos "{ \"name\":\"$1\" }"
}

github_remove_repo() {
    github_api DELETE "repos/$1"
}

github_close_issue() {
    github_api PATCH "repos/`target`/issues/$1" "{ \"state\":\"closed\" }"
}

github_assign_issue() {
    case "$1" in
	[0-9]|[0-9]*[0-9]) issue="$1" ;;
	*) user="$1" ;;
    esac
    if test -z "$issue"; then
	issue=$(github_api GET "repos/`target`/pulls" | get_branch_pr_number `user`:`current_branch`)
	test -z "$issue" && fail "Pull request not found"
    fi
    test -z "$user" && user=`user`
    github_api PATCH "repos/`target`/issues/$issue" "{ \"assignee\":\"$user\" }"
}

github_label() {
    issue=$(github_api GET "repos/`target`/pulls" | get_branch_pr_number `user`:`current_branch`)
    github_api POST "repos/`target`/issues/$issue/labels" "[ \"$1\" ]"
}

github_new_issue() {
    message=`mktemp`
    "$EDITOR" "$message"
    title=`head -1 "$message"`
    body=`tail -n +2 "$message" | sed 's/$/ \\\\n/'`
    echo "{ \"title\": \"$title\", \"body\": \"$body\" }" > TMP
    github_api POST "repos/`target`/issues" "@TMP"
    rm -f TMP
}

github_help() {
    cat <<EOF
git hub assign [<issue>] [<user>]
git hub clone <user/repo>
git hub close <issue>
git hub issue
git hub label <label>
git hub new <repo>
git hub pr
git hub pr <issue>
git hub rm <user/repo>
EOF
}

cmd="$1"
shift
case "$cmd" in
    assign) github_assign_issue "$@" ;;
    clone) github_clone "$@" ;;
    close) github_close_issue "$@" ;;
    help) github_help ;;
    issue) github_new_issue "$@" ;;
    label) github_label "$@" ;;
    new) github_new_repo "$@" ;;
    rm) github_remove_repo "$@" ;;
    pr) github_pull_request "$@" ;;
esac
