#!/bin/bash

set -x -e

current_branch() {
    git branch | awk '/^\* / { print $2 }'
}

tracking_branch() {
    git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD)
}

fast_forward() {
    branch="$1"
    if test -z "$branch"; then
	branch=`tracking_branch`
    fi
    git merge --ff-only "$branch"
}

fast_forward "$1"
